auctions/urls.py
from django.urls import path

from . import views

app_name = 'auctions'

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("listing", views.listing, name="listing"),
    path("item/<str:title>/", views.item, name="item"),
    path("category", views.category, name="category"),
    path("wishlist", views.wishlist, name="wishlist"),
    path("bid/<str:title>/", views.bid, name="bid")
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    id = models.AutoField(primary_key=True)
    pass

class Category(models.Model):
    id = models.AutoField(primary_key=True)
    categoryName= models.CharField(max_length=50)
    
    def __str__(self):
        return self.categoryName


class Listing(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=30)
    description = models.CharField(max_length=300)
    imageUrl = models.CharField(max_length=1000)
    price = models.FloatField()
    isActive = models.BooleanField(default=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name="listing_owner")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True, related_name="category")

    def __str__(self):
        return self.title

class Wishlist(models.Model):
    id = models.AutoField(primary_key=True)
    wishlist_user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name="wishlist_user")
    listItem = models.ForeignKey(Listing, on_delete=models.CASCADE, blank=True, null=True, related_name="wishlist_item")

    
class Bid(models.Model):
    amount = models.FloatField()
    bidder = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name="bidding_user")
    item = models.ForeignKey(Listing, on_delete=models.CASCADE, blank=True, null=True, related_name="bidding_item")



class Comment(models.Model):
    comment = models.CharField(max_length=300)
    comment_user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name="comment_user")
    commentItem = models.ForeignKey(Listing, on_delete=models.CASCADE, blank=True, null=True, related_name="comment_item")

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django import forms
from django.core.validators import MaxValueValidator
from builtins import max


from .models import User
from .models import Listing, Category, Wishlist, Bid, Comment


def index(request):
    listing = Listing.objects.filter(isActive=True)
    if 'unlist' in request.POST and request.POST['unlist'] != None:
        try:
            title = request.POST['unlist']
            item = Listing.objects.get(title=title)
            highest_bid = Bid.objects.filter(item=item).order_by('-amount').first()
            item.isActive = False
            item.save()
            if highest_bid:
                bid = highest_bid.bidder
                message = f"The auction for {item.title} has ended. {bid} won the auction with a bid of {highest_bid.amount}."
            else:
                message = f"The auction for {item.title} has ended. No one won the auction."
        except Listing.DoesNotExist:
            message = f"The item {title} does not exist."
    else:
        message = ""
    return render(request, "auctions/index.html", {'message': message, 'listing': listing})


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")


def listing(request):
    if request.method == "POST":
        title = request.POST['title']
        description = request.POST.get('description')
        imageUrl = request.POST.get('imageUrl')
        price = request.POST.get('price')
        category_id = request.POST.get('category')
        category = Category.objects.get(categoryName=category_id)
        user = request.user
        owner = user
        
        
        listing = Listing(title=title, description=description, imageUrl=imageUrl, price=price, category=category, owner=owner)
        listing.save()
        return redirect('index') 
    else:
        return render(request, "auctions/listing.html")


def item(request, title):
    if request.method == "POST":
        data = Listing.objects.get(title=title)
        if 'comment' in request.POST and request.POST['comment'] is not None:
            user = request.user
            post = request.POST['comment']
            com = Comment(comment=post, comment_user=user, commentItem=data)
            com.save()
        else:
            if Comment.objects.all() is not None:
                comment = Comment.objects.all()
                return render(request, "auctions/item.html", {'data': data, 'comment': comment})
            else:
                return render(request, "auctions/item.html", {'data': data})
    else:
        if Comment.objects.all() is not None:
                comment = Comment.objects.all()
                data = Listing.objects.get(title=title)
                return render(request, "auctions/item.html", {'data': data, 'comment': comment})
        else:
            data = Listing.objects.get(title=title)
            return render(request, "auctions/item.html", {'data': data})

def category(request):
    if request.method == "POST":
        categoryform = request.POST['category']
        category = Category.objects.get(categoryName=categoryform)
        data = Listing.objects.filter(category=category, isActive=True)
        return render(request, "auctions/category.html", {'data': data})

    else:
        return render(request, "auctions/category.html")

@login_required
def wishlist(request):
    if request.method == "POST":
        user = request.user
        if 'title'  in request.POST:
            title = request.POST['title']
            try:
                title = request.POST['title']
                listing = Listing.objects.get(title=title)
                wishlist_item, created = Wishlist.objects.get_or_create(wishlist_user=user, listItem=listing)
                if not created:
                    messages.info(request, "Item already in wishlist.")
                else:
                    wishlist_item.save()
            except listing.DoesNotExist:
                pass
        elif 'delete' in request.POST:
            title = request.POST['delete']
            try:
                listing = Listing.objects.get(title=title)
                wishlist_item = Wishlist.objects.filter(wishlist_user=user, listItem=listing)
                wishlist_item.delete()
            except (Listing.DoesNotExist, Wishlist.DoesNotExist):
                pass
        wishlist_items = Wishlist.objects.filter(wishlist_user=request.user)
        return render(request, "auctions/wishlist.html", {'wishlist': wishlist_items})
    else:
        wishlist_items = Wishlist.objects.filter(wishlist_user=request.user)
        return render(request, "auctions/wishlist.html", {'wishlist': wishlist_items})

@login_required
def bid(request, title):
    item = Listing.objects.get(title=title)
    highest_bid = Bid.objects.filter(item=item).order_by('-amount').first()
    if request.method == "POST":
        form = request.POST.get("bid")
        if form:
            new_bid = float(form)
            if highest_bid:
                current_highest_bid = float(highest_bid.amount)
                if new_bid > current_highest_bid:
                    highest_bid.amount = new_bid
                    highest_bid.bidder = request.user
                    highest_bid.save()
                    return redirect("auctions:item", title=title)
                else:
                    messages.error(request, "Your bid must be higher than the current highest bid.")
                    return render(request, 'auctions/bid.html', {'item': item, 'highest_bid': highest_bid})
            else:
                highest_bid = float(item.price)
                if new_bid > current_highest_bid:
                    bid = Bid(amount=new_bid, bidder=request.user, item=item)
                    bid.save()
                    return redirect("auctions:item", title=title)
                else:
                    messages.error(request, "Your bid must be higher than the price.")
                    return render(request, 'auctions/bid.html', {'item': item, 'highest_bid': highest_bid})
        else:
            messages.error(request, "Please enter a valid bid amount.")
            return render(request, 'auctions/bid.html', {'item': item, 'highest_bid': highest_bid})
    else:
        return render(request, 'auctions/bid.html', {'item': item, 'highest_bid': highest_bid})

auctions/templates/auctions/bid.html
{% extends "auctions/layout.html" %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <img src="{{ item.imageUrl }}" width="100%" height="300">
        </div>
        <div class="col-md-8">
            <h2>{{ item.title }}</h2>
            <p>{{ item.description }}</p>
            <hr>
            <label>Price:</label>
            <p>${{ item.price }}</p>
            <label>Category:</label>
            <p>{{ item.category }}</p>
            <label>Owner:</label>
            <p> {{ item.owner }}</p>
        </div>
    </div>
    <form method="POST" action="{% url 'auctions:wishlist' %}">
        {% csrf_token %}
        <input type="hidden" name="title" value="{{ item.title }}">
        <button type="submit"  class="btn btn-primary">Add to Wishlist</button>
    </form>
    <div class="container">
        <h2>Bid on {{ item.title }}</h2>
        <p>Current highest bid: ${{ highest_bid }}</p>
    </div>
</div>
    
{% endblock %}

auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}
{% block body %}
    <h2>Active Listings</h2>

    
    <form action="{% url 'auctions:category' %}" method="POST">
      {% csrf_token %}
        <label for="options">Select a category:</label>
            <select id="options" name="category">
              <option value="monitors">monitors</option>
              <option value="mouse">mouse</option>
              <option value="keyboards">keyboards</option>
              <option value="mouse pad">mouse pad</option>
            </select>
        <button type="submit">Select</button>
    </form>
    <div class="row">
        {% for dat in data %}
            <div class="col-md-2 border border-black">
                <p><a href="{% url 'auctions:item' title=dat.title %}">{{ dat }}</a></p>
                <img src="{{ dat.imageUrl }}" width="200" height="150">
                <p>{{ dat.description }}</p>
                <p>${{ dat.price }}</p>
            </div>
        {% endfor %}
    </div>
  {% endblock %}

auctions/templates/auctions/dad.html
def index(request):
    listing = Listing.objects.filter(isActive=True)
    if 'unlist' in request.POST and request.POST['unlist'] is not None:
        try:
            title = request.POST['unlist']
            item = Listing.objects.get(title=title)
            highest_bid = Bid.objects.filter(item=item).order_by('-amount').first()
            item.isActive = False

            if highest_bid:
                bid = highest_bid.bidder
                message = f"The auction for {item.title} has ended. {bid} won the auction with a bid of {highest_bid.amount}."
            else:
                message = f"The auction for {item.title} has ended. No one won the auction."
        except Listing.DoesNotExist:
            message = f"The item {title} does not exist."
    else:
        message = ""
    return render(request, "auctions/index.html", {'message': message, 'listing': listing})


    def index(request):
    listing = Listing.objects.filter(isActive=True)
    if 'unlist' in request.POST and request.POST['unlist'] is not None:
            title = request.POST['unlist']
            title = Listing.objects.get(title=title)
            highest_bid = Bid.objects.filter(item=title).order_by('-amount').first()
            title.isActive = False

            if highest_bid:
                bid = highest_bid.bidder
                message = f"This item is no longer available {bid} won this auction for {title.title}!!"
                return render(request, "auctions/index.html", {' message':  message, 'listing': listing})
            else:
                message = f"This item is no longer available nobody won this auction for {title.title}!!"
                return render(request, "auctions/index.html", {' message':  message, 'listing': listing})
    else:
        return render(request, "auctions/index.html", {'listing': listing})

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Active Listings</h2>

    
    <form action="{% url 'auctions:category' %}" method="POST">
      {% csrf_token %}
      <label for="options">Select a category:</label>
            <select id="options" name="category">
              <option value="monitors">monitors</option>
              <option value="mouse">mouse</option>
              <option value="keyboards">keyboards</option>
              <option value="mouse pad">mouse pad</option>
            </select>
        <button type="submit">Select</button>
      </form>

    <div class="row">
      {% if message %}
        <h2>{{message }}</h2>
      {% endif %}
      {% for list in listing %}
        <div class="col-md-2 border border-black">
            <p><a href="{% url 'auctions:item' title=list.title %}">{{ list }}</a></p>
            <img src="{{ list.imageUrl }}" width="200" height="150">
            <p>{{ list.description }}</p>
            <p>${{ list.price }}</p>
        </div>
      {% endfor %}
    </div>
    
{% endblock %}

auctions/templates/auctions/item.html
{% extends "auctions/layout.html" %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <img src="{{ data.imageUrl }}" width="100%" height="300">
        </div>
        <div class="col-md-8">
            <h2>{{ data.title }}</h2>
            <p>{{ data.description }}</p>
            <hr>
            <label>Price:</label>
            <p>${{ data.price }}</p>
            <label>Category:</label>
            <p>{{ data.category }}</p>
            <label>Owner:</label>
            <p> {{ data.owner }}</p>
        </div>
    </div>
    {% if user.is_authenticated %}
    <form method="POST" action="{% url 'auctions:index' %}">
        {% csrf_token %}
        <input type="hidden" name="unlist" value="{{ data.title }}">
        <button class="btn btn-danger">Unlistitem</button>
    </form>
    {% endif %}
    <form method="POST" action="{% url 'auctions:wishlist' %}">
        {% csrf_token %}
        <input type="hidden" name="title" value="{{ data.title }}">
        <button type="submit"  class="btn btn-primary">Add to Wishlist</button>
    </form>
    {% if data.title is not none %}
    <h2>Bid on {{ item.title }}</h2>
        <p>Current highest bid: ${{ highest_bid }}</p>
        <form method="post" action="{% url 'auctions:bid' title=data.title %}">
            {% csrf_token %}
            <label for="price">Price:</label>
            <input class="form-control" type="number" name="bid" id="price" placeholder="Ammount">
            <button type="submit" class="btn btn-primary">Place Bid</button>
        </form>
        <div>
            <form method="post" action="{% url 'auctions:item' title=data.title %}">
            {% csrf_token %}
            <label for="comment">Comment:</label>
            <textarea class="form-control" type="text" name="comment" id="comment" placeholder="Comment" rows="3"></textarea>
            <button type="submit" class="btn btn-primary">Enter</button>
            </form>
            {% endif %}
            {% for com in comment %} 
            <ul>
                <li>{{ com.comment_user }}: {{ com.comment }}</li>
            </ul>
            {% endfor %}
        </div>
</div>
    
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:wishlist' %}">Wishlist</a>
            </li>
            {% endif %}
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:listing' %}">List Items</a>
            </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>List items</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}
    
    <form action="{% url 'auctions:listing' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="title">Title:</label>
            <input autofocus class="form-control" type="text" name="title" id="title" placeholder="title">
        </div>
        <div class="form-group">
            <label for="description">Description:</label>
            <input class="form-control" type="text" name="description" id="description" placeholder="Description">
        </div>
        <div class="form-group">
            <label for="imageUrl">Image Url:</label>
            <input class="form-control" type="text" name="imageUrl" id="imageUrl" placeholder="Image Url">
        </div>
        <div class="form-group">
            <label for="price">Price:</label>
            <input class="form-control" type="number" name="price" id="price" placeholder="Price">
        </div>
        <div>
            <label for="options">Select a category:</label>
            <select id="options" name="category">
              <option value="monitors">monitors</option>
              <option value="mouse">mouse</option>
              <option value="keyboards">keyboards</option>
              <option value="mouse pad">mouse pad</option>
            </select>
        </div>
            
          
        <input class="btn btn-primary" type="submit" value="Submit">
    </form>
{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/wishlist.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>My Wishlist</h2>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
    <div class="row">
        {% for item in wishlist %}
          <div class="col-md-2 border border-black">
              <p><a href="{% url 'auctions:item' title=item.listItem.title %}">{{ item.listItem }}</a></p>
              <img src="{{ item.listItem.imageUrl }}" width="200" height="150">
              <p>{{ item.listItem.description }}</p>
              <p>${{ item.listItem.price }}</p>
              <form method="POST" action="{% url 'auctions:wishlist' %}">
                {% csrf_token %}
                <input type="hidden" name="delete" value="{{ item.listItem.title }}">
                <button type="submit"  class="btn btn-primary">Delete from Wishlist</button>
            </form>
          </div>
        {% endfor %}
    </div>
    
{% endblock %}